//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularReport_Activity6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.PassangerBookings = new HashSet<PassangerBooking>();
        }
    
        public int FlightNumber { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<int> AirlineID { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual InternationalFlight InternationalFlight { get; set; }
        public virtual LocalFlight LocalFlight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassangerBooking> PassangerBookings { get; set; }
    }
}
